project:
  type: website
  output-dir: ../_site

website:
  title: "ART FROM CODE"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: darkly
    css: styles.css
    toc: true



