---
title: "ART FROM CODE"
author: "Danielle Navarro"
execute:
  echo: true
format: 
  revealjs:
    theme: dark
    footer: "[art-from-code.netlify.app](https://art-from-code.netlify.app)"
---

```{r}
#| include: false
# save the built-in output hook
hook_output <- knitr::knit_hooks$get("output")

# set a new output hook to truncate text output
knitr::knit_hooks$set(output = function(x, options) {
  if (!is.null(n <- options$out.lines)) {
    x <- xfun::split_lines(x)
    if (length(x) > n) {
      # truncate the output
      x <- c(head(x, n), "...\n")
    }
    x <- paste(x, collapse = "\n")
  }
  hook_output(x, options)
})
```

## WiFi
	
- Username: conf22
- Password: together!

## Facilities
	
- Gender neutral bathroom: 
    - river side of Potomac Ballroom
- Meditation room: 
    - Potomac Dressing Room. (8am - 5pm, Mon - Thurs)
- Lactation room: 
    - National Harbor 9. (8am - 5pm, Mon - Thurs) 
    - The hotel also has a dedicated room behind reception

## Code of conduct

- The Code of Conduct and COVID policies can be found at [www.rstudio.com/conference/2022/2022-conf-code-of-conduct](https://www.rstudio.com/conference/2022/2022-conf-code-of-conduct/). Please review them carefully
- You can report Code of Conduct violations in person, by email, or by phone. Please see the policy linked above for contact information

## Mask policy

- RStudio requires that you wear a mask that fully covers your mouth and nose at all times in all public spaces 
- We strongly recommend that you use a correctly fitted N95, KN95, or similar particulate filtering mask
- We will have a limited supply available upon request

## Photography

- Red lanyard = Does not wish to be photographed 
- Please note lanyard colors before taking a photo
- Respect their choices

## Workshop housekeeping

- Written tutorial, data sets, exercises
    - Website: [art-from-code.netlify.app](https://art-from-code.netlify.app)
    - GitHub: [github.com/rstudio-conf-2022/art-from-code](https://github.com/rstudio-conf-2022/art-from-code)
- Instructors: 
    - Danielle Navarro

## Schedule, Day 1

| Time          | Activity                                                                              |
| :------------ | :------------------------------------------------------------------------------------ |
| 09:00 - 10:30 | Session 1: [Get started](https://art-from-code.netlify.com/day-1/session-1)           |
| 10:30 - 11:00 | *Coffee break*                                                                        |
| 11:00 - 12:30 | Session 2: [Spatial noise tricks](https://art-from-code.netlify.com/day-1/session-2)  |
| 12:30 - 13:30 | *Lunch break*                                                                         |
| 13:30 - 15:00 | Session 3: [Polygon tricks](https://art-from-code.netlify.com/day-1/session-3)        |
| 15:00 - 15:30 | *Coffee break*                                                                        |
| 15:30 - 17:00 | Session 4: [Shading tricks](https://art-from-code.netlify.com/day-1/session-4)        |

## Schedule, Day 2

| Time          | Activity                                                                                  |
| :------------ | :---------------------------------------------------------------------------------------- |
| 09:00 - 10:30 | Session 1: [Iterated function systems](https://art-from-code.netlify.com/day-2/session-1) |
| 10:30 - 11:00 | *Coffee break*                                                                            |
| 11:00 - 12:30 | Session 2: [Tiles and tesselations](https://art-from-code.netlify.com/day-2/session-2)    |
| 12:30 - 13:30 | *Lunch break*                                                                             |
| 13:30 - 15:00 | Session 3: [Pixel shaders](https://art-from-code.netlify.com/day-2/session-3)             |
| 15:00 - 15:30 | *Coffee break*                                                                            |
| 15:30 - 17:00 | Session 4: [Wrap up](https://art-from-code.netlify.com/day-2/session-4)                   |
